//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace GestioneAnagraficaReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws.lottomatica.scga.it", ConfigurationName = "GestioneAnagraficaReference.RegistraContoGioco")]
    public interface RegistraContoGioco
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<GestioneAnagraficaReference.modificaContoGiocoResponse> modificaContoGiocoAsync(GestioneAnagraficaReference.modificaContoGiocoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<GestioneAnagraficaReference.registraContoGiocoResponse1> registraContoGiocoAsync(GestioneAnagraficaReference.registraContoGiocoRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.lottomatica.scga.it/types")]
    public partial class RegistraContoGiocoResponse
    {

        private string codiceRisultatoField;

        private string datiFirmatiField;

        private string descrizioneRisultatoField;

        private string firmaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public string codiceRisultato
        {
            get
            {
                return this.codiceRisultatoField;
            }
            set
            {
                this.codiceRisultatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string datiFirmati
        {
            get
            {
                return this.datiFirmatiField;
            }
            set
            {
                this.datiFirmatiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string descrizioneRisultato
        {
            get
            {
                return this.descrizioneRisultatoField;
            }
            set
            {
                this.descrizioneRisultatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 3)]
        public string firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "modificaContoGioco", WrapperNamespace = "http://ws.lottomatica.scga.it", IsWrapped = true)]
    public partial class modificaContoGiocoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string String_1;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string String_2;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string String_3;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string String_4;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string String_5;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string String_6;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string String_7;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string String_8;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string String_9;

        public modificaContoGiocoRequest()
        {
        }

        public modificaContoGiocoRequest(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6, string String_7, string String_8, string String_9)
        {
            this.String_1 = String_1;
            this.String_2 = String_2;
            this.String_3 = String_3;
            this.String_4 = String_4;
            this.String_5 = String_5;
            this.String_6 = String_6;
            this.String_7 = String_7;
            this.String_8 = String_8;
            this.String_9 = String_9;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "modificaContoGiocoResponse", WrapperNamespace = "http://ws.lottomatica.scga.it", IsWrapped = true)]
    public partial class modificaContoGiocoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public GestioneAnagraficaReference.RegistraContoGiocoResponse result;

        public modificaContoGiocoResponse()
        {
        }

        public modificaContoGiocoResponse(GestioneAnagraficaReference.RegistraContoGiocoResponse result)
        {
            this.result = result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "registraContoGioco", WrapperNamespace = "http://ws.lottomatica.scga.it", IsWrapped = true)]
    public partial class registraContoGiocoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string String_1;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string String_2;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public string String_3;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string String_4;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string String_5;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 5)]
        public string String_6;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 6)]
        public string String_7;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 7)]
        public string String_8;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 8)]
        public string String_9;

        public registraContoGiocoRequest()
        {
        }

        public registraContoGiocoRequest(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6, string String_7, string String_8, string String_9)
        {
            this.String_1 = String_1;
            this.String_2 = String_2;
            this.String_3 = String_3;
            this.String_4 = String_4;
            this.String_5 = String_5;
            this.String_6 = String_6;
            this.String_7 = String_7;
            this.String_8 = String_8;
            this.String_9 = String_9;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "registraContoGiocoResponse", WrapperNamespace = "http://ws.lottomatica.scga.it", IsWrapped = true)]
    public partial class registraContoGiocoResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public GestioneAnagraficaReference.RegistraContoGiocoResponse result;

        public registraContoGiocoResponse1()
        {
        }

        public registraContoGiocoResponse1(GestioneAnagraficaReference.RegistraContoGiocoResponse result)
        {
            this.result = result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface RegistraContoGiocoChannel : GestioneAnagraficaReference.RegistraContoGioco, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class RegistraContoGiocoClient : System.ServiceModel.ClientBase<GestioneAnagraficaReference.RegistraContoGioco>, GestioneAnagraficaReference.RegistraContoGioco
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public RegistraContoGiocoClient() :
                base(RegistraContoGiocoClient.GetDefaultBinding(), RegistraContoGiocoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RegistraContoGiocoPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RegistraContoGiocoClient(EndpointConfiguration endpointConfiguration) :
                base(RegistraContoGiocoClient.GetBindingForEndpoint(endpointConfiguration), RegistraContoGiocoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RegistraContoGiocoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(RegistraContoGiocoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RegistraContoGiocoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(RegistraContoGiocoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public RegistraContoGiocoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<GestioneAnagraficaReference.modificaContoGiocoResponse> modificaContoGiocoAsync(GestioneAnagraficaReference.modificaContoGiocoRequest request)
        {
            return base.Channel.modificaContoGiocoAsync(request);
        }

        public System.Threading.Tasks.Task<GestioneAnagraficaReference.registraContoGiocoResponse1> registraContoGiocoAsync(GestioneAnagraficaReference.registraContoGiocoRequest request)
        {
            return base.Channel.registraContoGiocoAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RegistraContoGiocoPort || endpointConfiguration == EndpointConfiguration.RegistraContoGiocoPortProd))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode= BasicHttpSecurityMode.None;
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RegistraContoGiocoPort))
            {
                return new System.ServiceModel.EndpointAddress("https://litnew-cat.grattaevinci.com/registracontogioco_ejb/RegistraContoGioco");
            }
            else if (endpointConfiguration == EndpointConfiguration.RegistraContoGiocoPortProd)
            {
                return new System.ServiceModel.EndpointAddress("https://lit.grattaevinci.com/registracontogioco_ejb/RegistraContoGioco");
            }
            
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RegistraContoGiocoClient.GetBindingForEndpoint(EndpointConfiguration.RegistraContoGiocoPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RegistraContoGiocoClient.GetEndpointAddress(EndpointConfiguration.RegistraContoGiocoPort);
        }

        public enum EndpointConfiguration
        {

            RegistraContoGiocoPort,
            RegistraContoGiocoPortProd,
        }
    }
}
