//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetirTestApi.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetirTestApi.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account identifier is not valid. There&apos;s no customer for the account selected..
        /// </summary>
        internal static string INVALID_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer birth date is not valid. Customer must be older than 17 years old..
        /// </summary>
        internal static string INVALID_CUSTOMER_BDATE {
            get {
                return ResourceManager.GetString("INVALID_CUSTOMER_BDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer IBAN has not a valid format..
        /// </summary>
        internal static string INVALID_CUSTOMER_IBAN {
            get {
                return ResourceManager.GetString("INVALID_CUSTOMER_IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer identifier is not valid. There&apos;s no customer for the id selected..
        /// </summary>
        internal static string INVALID_CUSTOMER_ID {
            get {
                return ResourceManager.GetString("INVALID_CUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer national identifier is already existing in our archives. Please make sure to register a new customer..
        /// </summary>
        internal static string INVALID_CUSTOMER_NID {
            get {
                return ResourceManager.GetString("INVALID_CUSTOMER_NID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date range is not valid..
        /// </summary>
        internal static string INVALID_FROM_TO {
            get {
                return ResourceManager.GetString("INVALID_FROM_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account identifier is missing..
        /// </summary>
        internal static string MISSING_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("MISSING_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer account type si missing..
        /// </summary>
        internal static string MISSING_ACCOUNTYPE {
            get {
                return ResourceManager.GetString("MISSING_ACCOUNTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer birth date is missing..
        /// </summary>
        internal static string MISSING_CUSTOMER_BDATE {
            get {
                return ResourceManager.GetString("MISSING_CUSTOMER_BDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer first name is missing..
        /// </summary>
        internal static string MISSING_CUSTOMER_FIRSTNAME {
            get {
                return ResourceManager.GetString("MISSING_CUSTOMER_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer identifier is missing..
        /// </summary>
        internal static string MISSING_CUSTOMER_ID {
            get {
                return ResourceManager.GetString("MISSING_CUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer last name is missing..
        /// </summary>
        internal static string MISSING_CUSTOMER_LASTNAME {
            get {
                return ResourceManager.GetString("MISSING_CUSTOMER_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer national identifier is missing..
        /// </summary>
        internal static string MISSING_CUSTOMER_NID {
            get {
                return ResourceManager.GetString("MISSING_CUSTOMER_NID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of range start is missing..
        /// </summary>
        internal static string MISSING_DATE_FROM {
            get {
                return ResourceManager.GetString("MISSING_DATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of range end is missing..
        /// </summary>
        internal static string MISSING_DATE_TO {
            get {
                return ResourceManager.GetString("MISSING_DATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer IBAN for the current account is missing..
        /// </summary>
        internal static string MISSING_IBAN {
            get {
                return ResourceManager.GetString("MISSING_IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of the transaction is missing..
        /// </summary>
        internal static string MISSING_TRANSACTION_AMOUNT {
            get {
                return ResourceManager.GetString("MISSING_TRANSACTION_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Withdrawal flag is missing and it&apos;s required to define a transaction..
        /// </summary>
        internal static string MISSING_TRANSACTION_ISFLAG {
            get {
                return ResourceManager.GetString("MISSING_TRANSACTION_ISFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user responsible to create a customer is missing..
        /// </summary>
        internal static string MISSING_USER {
            get {
                return ResourceManager.GetString("MISSING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction amount cannot have more than 2 decimal places..
        /// </summary>
        internal static string TRANSACTION_AMOUNT_DECIMALS {
            get {
                return ResourceManager.GetString("TRANSACTION_AMOUNT_DECIMALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction amount is invalid because it&apos;s out of range..
        /// </summary>
        internal static string TRANSACTION_AMOUNT_OUTOFRANGE {
            get {
                return ResourceManager.GetString("TRANSACTION_AMOUNT_OUTOFRANGE", resourceCulture);
            }
        }
    }
}
