//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClrPgad.PgadCommunication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgadGatewayResponse", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgadGatewayGenericError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgadGatewayStatoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgadGatewayStatoGenericError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneGenericError))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioGenericError))]
    public partial class PgadGatewayResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _descrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short _esitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _idRicevutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _idTransazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _timestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _descrizione {
            get {
                return this._descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this._descrizioneField, value) != true)) {
                    this._descrizioneField = value;
                    this.RaisePropertyChanged("_descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short _esito {
            get {
                return this._esitoField;
            }
            set {
                if ((this._esitoField.Equals(value) != true)) {
                    this._esitoField = value;
                    this.RaisePropertyChanged("_esito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _idRicevuta {
            get {
                return this._idRicevutaField;
            }
            set {
                if ((object.ReferenceEquals(this._idRicevutaField, value) != true)) {
                    this._idRicevutaField = value;
                    this.RaisePropertyChanged("_idRicevuta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _idTransazione {
            get {
                return this._idTransazioneField;
            }
            set {
                if ((this._idTransazioneField.Equals(value) != true)) {
                    this._idTransazioneField = value;
                    this.RaisePropertyChanged("_idTransazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _success {
            get {
                return this._successField;
            }
            set {
                if ((this._successField.Equals(value) != true)) {
                    this._successField = value;
                    this.RaisePropertyChanged("_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _timestamp {
            get {
                return this._timestampField;
            }
            set {
                if ((this._timestampField.Equals(value) != true)) {
                    this._timestampField = value;
                    this.RaisePropertyChanged("_timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgadGatewayGenericError", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    public partial class PgadGatewayGenericError : ClrPgad.PgadCommunication.PgadGatewayResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgadGatewayStatoResponse", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgadGatewayStatoGenericError))]
    public partial class PgadGatewayStatoResponse : ClrPgad.PgadCommunication.PgadGatewayResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CausaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceContoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdCnContoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReteContoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Causale {
            get {
                return this.CausaleField;
            }
            set {
                if ((this.CausaleField.Equals(value) != true)) {
                    this.CausaleField = value;
                    this.RaisePropertyChanged("Causale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceConto {
            get {
                return this.CodiceContoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceContoField, value) != true)) {
                    this.CodiceContoField = value;
                    this.RaisePropertyChanged("CodiceConto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdCnConto {
            get {
                return this.IdCnContoField;
            }
            set {
                if ((this.IdCnContoField.Equals(value) != true)) {
                    this.IdCnContoField = value;
                    this.RaisePropertyChanged("IdCnConto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReteConto {
            get {
                return this.IdReteContoField;
            }
            set {
                if ((this.IdReteContoField.Equals(value) != true)) {
                    this.IdReteContoField = value;
                    this.RaisePropertyChanged("IdReteConto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stato {
            get {
                return this.StatoField;
            }
            set {
                if ((this.StatoField.Equals(value) != true)) {
                    this.StatoField = value;
                    this.RaisePropertyChanged("Stato");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgadGatewayStatoGenericError", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    public partial class PgadGatewayStatoGenericError : ClrPgad.PgadCommunication.PgadGatewayStatoResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgdaGatewayRiepilogoOperazioniMovimentazioneResponse", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneGenericError))]
    public partial class PgdaGatewayRiepilogoOperazioniMovimentazioneResponse : ClrPgad.PgadCommunication.PgadGatewayResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClrPgad.PgadCommunication.DettaglioOperazioniMovimentazione[] OperazioniField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClrPgad.PgadCommunication.DettaglioOperazioniMovimentazione[] Operazioni {
            get {
                return this.OperazioniField;
            }
            set {
                if ((object.ReferenceEquals(this.OperazioniField, value) != true)) {
                    this.OperazioniField = value;
                    this.RaisePropertyChanged("Operazioni");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgdaGatewayRiepilogoOperazioniMovimentazioneGenericError", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    public partial class PgdaGatewayRiepilogoOperazioniMovimentazioneGenericError : ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgdaGatewayRiepilogoOperazioniServizioResponse", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioGenericError))]
    public partial class PgdaGatewayRiepilogoOperazioniServizioResponse : ClrPgad.PgadCommunication.PgadGatewayResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClrPgad.PgadCommunication.DettaglioOperazioniServizio[] OperazioniField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClrPgad.PgadCommunication.DettaglioOperazioniServizio[] Operazioni {
            get {
                return this.OperazioniField;
            }
            set {
                if ((object.ReferenceEquals(this.OperazioniField, value) != true)) {
                    this.OperazioniField = value;
                    this.RaisePropertyChanged("Operazioni");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PgdaGatewayRiepilogoOperazioniServizioGenericError", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    public partial class PgdaGatewayRiepilogoOperazioniServizioGenericError : ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioOperazioniMovimentazione", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Pgad")]
    [System.SerializableAttribute()]
    public partial class DettaglioOperazioniMovimentazione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        private sbyte causaleMovimentoFieldField;
        
        private int numeroOperazioniFieldField;
        
        private long totaleImportoFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public sbyte causaleMovimentoField {
            get {
                return this.causaleMovimentoFieldField;
            }
            set {
                if ((this.causaleMovimentoFieldField.Equals(value) != true)) {
                    this.causaleMovimentoFieldField = value;
                    this.RaisePropertyChanged("causaleMovimentoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroOperazioniField {
            get {
                return this.numeroOperazioniFieldField;
            }
            set {
                if ((this.numeroOperazioniFieldField.Equals(value) != true)) {
                    this.numeroOperazioniFieldField = value;
                    this.RaisePropertyChanged("numeroOperazioniField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long totaleImportoField {
            get {
                return this.totaleImportoFieldField;
            }
            set {
                if ((this.totaleImportoFieldField.Equals(value) != true)) {
                    this.totaleImportoFieldField = value;
                    this.RaisePropertyChanged("totaleImportoField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioOperazioniServizio", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Pgad")]
    [System.SerializableAttribute()]
    public partial class DettaglioOperazioniServizio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        private sbyte causaleServizioFieldField;
        
        private int numeroOperazioniFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public sbyte causaleServizioField {
            get {
                return this.causaleServizioFieldField;
            }
            set {
                if ((this.causaleServizioFieldField.Equals(value) != true)) {
                    this.causaleServizioFieldField = value;
                    this.RaisePropertyChanged("causaleServizioField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroOperazioniField {
            get {
                return this.numeroOperazioniFieldField;
            }
            set {
                if ((this.numeroOperazioniFieldField.Equals(value) != true)) {
                    this.numeroOperazioniFieldField = value;
                    this.RaisePropertyChanged("numeroOperazioniField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAUSALE_CAMBIO_STATO_CONTO", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    public enum CAUSALE_CAMBIO_STATO_CONTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DA_AAMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DAL_CONCESSIONARIO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DAL_TITOLARE_CONTO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DA_AUTORITA_GIUDIZIARIA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DA_AAMS_DECESSO = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DAL_CONCESSIONARIO_PER_MANCATO_INVIO_DOC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICHIESTO_DAL_CONCESSIONARIO_PER_FRODE = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STATO_CONTO", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    public enum STATO_CONTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APERTO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOSPESO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHIUSO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DORMIENTE = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bonus", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    [System.SerializableAttribute()]
    public partial class Bonus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceFamigliaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImportoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoGiocoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodiceFamiglia {
            get {
                return this.CodiceFamigliaField;
            }
            set {
                if ((this.CodiceFamigliaField.Equals(value) != true)) {
                    this.CodiceFamigliaField = value;
                    this.RaisePropertyChanged("CodiceFamiglia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Importo {
            get {
                return this.ImportoField;
            }
            set {
                if ((this.ImportoField.Equals(value) != true)) {
                    this.ImportoField = value;
                    this.RaisePropertyChanged("Importo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoGioco {
            get {
                return this.TipoGiocoField;
            }
            set {
                if ((this.TipoGiocoField.Equals(value) != true)) {
                    this.TipoGiocoField = value;
                    this.RaisePropertyChanged("TipoGioco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAUSALE_MOVIMENTO", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    public enum CAUSALE_MOVIMENTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICARICA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STORNO_RICARICA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRELIEVO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STORNO_PRELIEVO = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COSTI_SERVIZI_AGGIUNTIVI = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STORNO_COSTI_SERVIZI_AGGIUNTIVI = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MEZZO_PAGAMENTO", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    public enum MEZZO_PAGAMENTO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONTANTI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CARTA_CREDITO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CARTA_PREPAGATA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BONIFICO_BANCARIO_POSTALE = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOLLETTINO_POSTALE = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASSEGNO_CONTO_CORRENTE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASSEGNO_CIRCOLARE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VAGLIA_POSTALE = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RICARICA_SCRATCH = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALTRO = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMEL = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONTO_DI_GIOCO = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONVERSIONE_BONUS = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E_WALLET = 14,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPO_STORNO", Namespace="http://schemas.datacontract.org/2004/07/PgadCommunication.Business")]
    public enum TIPO_STORNO : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORMALE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHARGE_BACK = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.intralot.it/pgad", ConfigurationName="PgadCommunication.IPgad")]
    public interface IPgad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/ApriContoPersonaFisica", ReplyAction="http://www.intralot.it/pgad/IPgad/ApriContoPersonaFisicaResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse ApriContoPersonaFisica(
                    long Idtransazione, 
                    string PartitaIva, 
                    int CodiceAgenzia, 
                    string CodiceConto, 
                    string CodiceFiscale, 
                    string Cognome, 
                    string Nome, 
                    char Sesso, 
                    string Email, 
                    string UserName, 
                    string Comune_Nazione_Nascita, 
                    string ProvinciaNascita, 
                    System.DateTime DataNascita, 
                    string IndirizzoResidenza, 
                    string ComuneResidenza, 
                    string ProvinciaResidenza, 
                    string CapResidenza, 
                    System.DateTime DataRilascioDocumento, 
                    string AutoritaRilascioDocumento, 
                    string LocalicaRilascioDocumento, 
                    string NumeroDocumento, 
                    int IdTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/AggiornaDocumento", ReplyAction="http://www.intralot.it/pgad/IPgad/AggiornaDocumentoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse AggiornaDocumento(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceConto, System.DateTime DataRilascioDocumento, string AutoritaRilascioDocumento, string LocalicaRilascioDocumento, string NumeroDocumento, int IdTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/SubRegistrazione", ReplyAction="http://www.intralot.it/pgad/IPgad/SubRegistrazioneResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse SubRegistrazione(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/StatoConto", ReplyAction="http://www.intralot.it/pgad/IPgad/StatoContoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayStatoResponse StatoConto(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/CambioStato", ReplyAction="http://www.intralot.it/pgad/IPgad/CambioStatoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse CambioStato(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto, ClrPgad.PgadCommunication.CAUSALE_CAMBIO_STATO_CONTO CausaleCambioStato, ClrPgad.PgadCommunication.STATO_CONTO StatoConto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/ModificaProvinciaResidenza", ReplyAction="http://www.intralot.it/pgad/IPgad/ModificaProvinciaResidenzaResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse ModificaProvinciaResidenza(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto, string ProvinciaResidenza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MigrazioneContoGioco", ReplyAction="http://www.intralot.it/pgad/IPgad/MigrazioneContoGiocoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MigrazioneContoGioco(long Idtransazione, string PartitaIva, int IdReteContoOriginario, int TitolareSistemaOriginario, string CodiceContoOriginario, int IdReteContoDestinazione, int TitolareSistemaDestinazione, string CodiceContoDestinazione, string CodiceFiscale, int ImportoSaldo, System.DateTime DataSaldo, System.Data.DataSet ListBonusPresenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MigrazioneContoGioco_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/MigrazioneContoGioco_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MigrazioneContoGioco_V2(long Idtransazione, string PartitaIva, int IdReteContoOriginario, int TitolareSistemaOriginario, string CodiceContoOriginario, int IdReteContoDestinazione, int TitolareSistemaDestinazione, string CodiceContoDestinazione, string CodiceFiscale, int ImportoSaldo, System.DateTime DataSaldo, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MovimentazioneBonus", ReplyAction="http://www.intralot.it/pgad/IPgad/MovimentazioneBonusResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneBonus(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusDaAssegnare, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MovimentazioneBonus_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/MovimentazioneBonus_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneBonus_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusDaAssegnare, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/StornoBonus", ReplyAction="http://www.intralot.it/pgad/IPgad/StornoBonusResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse StornoBonus(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusDaAssegnare, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/StornoBonus_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/StornoBonus_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse StornoBonus_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusDaAssegnare, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MovimentazioneCredito", ReplyAction="http://www.intralot.it/pgad/IPgad/MovimentazioneCreditoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneCredito(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/MovimentazioneCredito_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/MovimentazioneCredito_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneCredito_V2(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/StornoMovimentazioneCredito", ReplyAction="http://www.intralot.it/pgad/IPgad/StornoMovimentazioneCreditoResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse StornoMovimentazioneCredito(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, ClrPgad.PgadCommunication.TIPO_STORNO TipoStorno, string idRicevutaDaStornare, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/StornoMovimentazioneCredito_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/StornoMovimentazioneCredito_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse StornoMovimentazioneCredito_V2(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, ClrPgad.PgadCommunication.TIPO_STORNO TipoStorno, string idRicevutaDaStornare, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/SaldoContoUtente", ReplyAction="http://www.intralot.it/pgad/IPgad/SaldoContoUtenteResponse")]
        ClrPgad.PgadCommunication.PgadGatewayResponse SaldoContoUtente(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/SaldoContoUtente_V2", ReplyAction="http://www.intralot.it/pgad/IPgad/SaldoContoUtente_V2Response")]
        ClrPgad.PgadCommunication.PgadGatewayResponse SaldoContoUtente_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/RiepilogoOperazioniMovimentazione", ReplyAction="http://www.intralot.it/pgad/IPgad/RiepilogoOperazioniMovimentazioneResponse")]
        ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneResponse RiepilogoOperazioniMovimentazione(long Idtransazione, string PartitaIva, int TitolareSistema, System.DateTime Data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intralot.it/pgad/IPgad/RiepilogoOperazioniServizio", ReplyAction="http://www.intralot.it/pgad/IPgad/RiepilogoOperazioniServizioResponse")]
        ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioResponse RiepilogoOperazioniServizio(long Idtransazione, string PartitaIva, int TitolareSistema, System.DateTime Data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPgadChannel : ClrPgad.PgadCommunication.IPgad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PgadClient : System.ServiceModel.ClientBase<ClrPgad.PgadCommunication.IPgad>, ClrPgad.PgadCommunication.IPgad {
        
        public PgadClient() {
        }
        
        public PgadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PgadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PgadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PgadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse ApriContoPersonaFisica(
                    long Idtransazione, 
                    string PartitaIva, 
                    int CodiceAgenzia, 
                    string CodiceConto, 
                    string CodiceFiscale, 
                    string Cognome, 
                    string Nome, 
                    char Sesso, 
                    string Email, 
                    string UserName, 
                    string Comune_Nazione_Nascita, 
                    string ProvinciaNascita, 
                    System.DateTime DataNascita, 
                    string IndirizzoResidenza, 
                    string ComuneResidenza, 
                    string ProvinciaResidenza, 
                    string CapResidenza, 
                    System.DateTime DataRilascioDocumento, 
                    string AutoritaRilascioDocumento, 
                    string LocalicaRilascioDocumento, 
                    string NumeroDocumento, 
                    int IdTipoDocumento) {
            return base.Channel.ApriContoPersonaFisica(Idtransazione, PartitaIva, CodiceAgenzia, CodiceConto, CodiceFiscale, Cognome, Nome, Sesso, Email, UserName, Comune_Nazione_Nascita, ProvinciaNascita, DataNascita, IndirizzoResidenza, ComuneResidenza, ProvinciaResidenza, CapResidenza, DataRilascioDocumento, AutoritaRilascioDocumento, LocalicaRilascioDocumento, NumeroDocumento, IdTipoDocumento);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse AggiornaDocumento(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceConto, System.DateTime DataRilascioDocumento, string AutoritaRilascioDocumento, string LocalicaRilascioDocumento, string NumeroDocumento, int IdTipoDocumento) {
            return base.Channel.AggiornaDocumento(Idtransazione, PartitaIva, CodiceAgenzia, CodiceConto, DataRilascioDocumento, AutoritaRilascioDocumento, LocalicaRilascioDocumento, NumeroDocumento, IdTipoDocumento);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse SubRegistrazione(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto) {
            return base.Channel.SubRegistrazione(Idtransazione, PartitaIva, CodiceAgenzia, CodiceContratto);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayStatoResponse StatoConto(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto) {
            return base.Channel.StatoConto(Idtransazione, PartitaIva, CodiceAgenzia, CodiceContratto);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse CambioStato(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto, ClrPgad.PgadCommunication.CAUSALE_CAMBIO_STATO_CONTO CausaleCambioStato, ClrPgad.PgadCommunication.STATO_CONTO StatoConto) {
            return base.Channel.CambioStato(Idtransazione, PartitaIva, CodiceAgenzia, CodiceContratto, CausaleCambioStato, StatoConto);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse ModificaProvinciaResidenza(long Idtransazione, string PartitaIva, int CodiceAgenzia, string CodiceContratto, string ProvinciaResidenza) {
            return base.Channel.ModificaProvinciaResidenza(Idtransazione, PartitaIva, CodiceAgenzia, CodiceContratto, ProvinciaResidenza);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MigrazioneContoGioco(long Idtransazione, string PartitaIva, int IdReteContoOriginario, int TitolareSistemaOriginario, string CodiceContoOriginario, int IdReteContoDestinazione, int TitolareSistemaDestinazione, string CodiceContoDestinazione, string CodiceFiscale, int ImportoSaldo, System.DateTime DataSaldo, System.Data.DataSet ListBonusPresenti) {
            return base.Channel.MigrazioneContoGioco(Idtransazione, PartitaIva, IdReteContoOriginario, TitolareSistemaOriginario, CodiceContoOriginario, IdReteContoDestinazione, TitolareSistemaDestinazione, CodiceContoDestinazione, CodiceFiscale, ImportoSaldo, DataSaldo, ListBonusPresenti);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MigrazioneContoGioco_V2(long Idtransazione, string PartitaIva, int IdReteContoOriginario, int TitolareSistemaOriginario, string CodiceContoOriginario, int IdReteContoDestinazione, int TitolareSistemaDestinazione, string CodiceContoDestinazione, string CodiceFiscale, int ImportoSaldo, System.DateTime DataSaldo, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti) {
            return base.Channel.MigrazioneContoGioco_V2(Idtransazione, PartitaIva, IdReteContoOriginario, TitolareSistemaOriginario, CodiceContoOriginario, IdReteContoDestinazione, TitolareSistemaDestinazione, CodiceContoDestinazione, CodiceFiscale, ImportoSaldo, DataSaldo, ListBonusPresenti);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneBonus(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusDaAssegnare, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.MovimentazioneBonus(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusDaAssegnare, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneBonus_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusDaAssegnare, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.MovimentazioneBonus_V2(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusDaAssegnare, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse StornoBonus(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusDaAssegnare, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.StornoBonus(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusDaAssegnare, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse StornoBonus_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusDaAssegnare, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.StornoBonus_V2(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusDaAssegnare, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneCredito(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.MovimentazioneCredito(Idtransazione, PartitaIva, CausaleDiMovimento, MezzoDiPagamento, ContoDiGioco, TitolareSistema, ImportoMovimento, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse MovimentazioneCredito_V2(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.MovimentazioneCredito_V2(Idtransazione, PartitaIva, CausaleDiMovimento, MezzoDiPagamento, ContoDiGioco, TitolareSistema, ImportoMovimento, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse StornoMovimentazioneCredito(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, ClrPgad.PgadCommunication.TIPO_STORNO TipoStorno, string idRicevutaDaStornare, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.StornoMovimentazioneCredito(Idtransazione, PartitaIva, CausaleDiMovimento, MezzoDiPagamento, TipoStorno, idRicevutaDaStornare, ContoDiGioco, TitolareSistema, ImportoMovimento, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse StornoMovimentazioneCredito_V2(long Idtransazione, string PartitaIva, ClrPgad.PgadCommunication.CAUSALE_MOVIMENTO CausaleDiMovimento, ClrPgad.PgadCommunication.MEZZO_PAGAMENTO MezzoDiPagamento, ClrPgad.PgadCommunication.TIPO_STORNO TipoStorno, string idRicevutaDaStornare, string ContoDiGioco, int TitolareSistema, int ImportoMovimento, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.StornoMovimentazioneCredito_V2(Idtransazione, PartitaIva, CausaleDiMovimento, MezzoDiPagamento, TipoStorno, idRicevutaDaStornare, ContoDiGioco, TitolareSistema, ImportoMovimento, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse SaldoContoUtente(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, System.Data.DataSet ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.SaldoContoUtente(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgadGatewayResponse SaldoContoUtente_V2(long Idtransazione, string PartitaIva, string ContoDiGioco, int TitolareSistema, ClrPgad.PgadCommunication.Bonus[] ListBonusPresenti, int SaldoUtente, System.DateTime DataSaldo) {
            return base.Channel.SaldoContoUtente_V2(Idtransazione, PartitaIva, ContoDiGioco, TitolareSistema, ListBonusPresenti, SaldoUtente, DataSaldo);
        }
        
        public ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniMovimentazioneResponse RiepilogoOperazioniMovimentazione(long Idtransazione, string PartitaIva, int TitolareSistema, System.DateTime Data) {
            return base.Channel.RiepilogoOperazioniMovimentazione(Idtransazione, PartitaIva, TitolareSistema, Data);
        }
        
        public ClrPgad.PgadCommunication.PgdaGatewayRiepilogoOperazioniServizioResponse RiepilogoOperazioniServizio(long Idtransazione, string PartitaIva, int TitolareSistema, System.DateTime Data) {
            return base.Channel.RiepilogoOperazioniServizio(Idtransazione, PartitaIva, TitolareSistema, Data);
        }
    }
}
