//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.4952
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=2.0.50727.3038.
// 
namespace AnagraficaContiGiocoForniture
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class anag_conti
    {

        private string id_fornituraField;

        private string num_recordField;

        private conto[] contoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string id_fornitura
        {
            get
            {
                return this.id_fornituraField;
            }
            set
            {
                this.id_fornituraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string num_record
        {
            get
            {
                return this.num_recordField;
            }
            set
            {
                this.num_recordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conto")]
        public conto[] conto
        {
            get
            {
                return this.contoField;
            }
            set
            {
                this.contoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class conto
    {

        private string progField;

        private string nicknameField;

        private string emailField;

        private string id_contoField;

        private System.DateTime data_attivazioneField;

        private cod_rete cod_reteField;

        private string cod_concField;

        private soggetto soggettoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string prog
        {
            get
            {
                return this.progField;
            }
            set
            {
                this.progField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string nickname
        {
            get
            {
                return this.nicknameField;
            }
            set
            {
                this.nicknameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string id_conto
        {
            get
            {
                return this.id_contoField;
            }
            set
            {
                this.id_contoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime data_attivazione
        {
            get
            {
                return this.data_attivazioneField;
            }
            set
            {
                this.data_attivazioneField = value;
            }
        }

        /// <remarks/>
        public cod_rete cod_rete
        {
            get
            {
                return this.cod_reteField;
            }
            set
            {
                this.cod_reteField = value;
            }
        }

        /// <remarks/>
        public string cod_conc
        {
            get
            {
                return this.cod_concField;
            }
            set
            {
                this.cod_concField = value;
            }
        }

        /// <remarks/>
        public soggetto soggetto
        {
            get
            {
                return this.soggettoField;
            }
            set
            {
                this.soggettoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum cod_rete
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class soggetto
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona_fisica", typeof(persona_fisica))]
        [System.Xml.Serialization.XmlElementAttribute("persona_giuridica", typeof(persona_giuridica))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class persona_fisica
    {

        private string id_soggettoField;

        private string nomeField;

        private string cognomeField;

        private sesso sessoField;

        private System.DateTime data_nascitaField;

        private string comune_nascitaField;

        private string prov_nascitaField;

        private string prov_residenzaField;

        /// <remarks/>
        public string id_soggetto
        {
            get
            {
                return this.id_soggettoField;
            }
            set
            {
                this.id_soggettoField = value;
            }
        }

        /// <remarks/>
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        public string cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
            }
        }

        /// <remarks/>
        public sesso sesso
        {
            get
            {
                return this.sessoField;
            }
            set
            {
                this.sessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime data_nascita
        {
            get
            {
                return this.data_nascitaField;
            }
            set
            {
                this.data_nascitaField = value;
            }
        }

        /// <remarks/>
        public string comune_nascita
        {
            get
            {
                return this.comune_nascitaField;
            }
            set
            {
                this.comune_nascitaField = value;
            }
        }

        /// <remarks/>
        public string prov_nascita
        {
            get
            {
                return this.prov_nascitaField;
            }
            set
            {
                this.prov_nascitaField = value;
            }
        }

        /// <remarks/>
        public string prov_residenza
        {
            get
            {
                return this.prov_residenzaField;
            }
            set
            {
                this.prov_residenzaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum sesso
    {

        /// <remarks/>
        M,

        /// <remarks/>
        F,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class persona_giuridica
    {

        private string id_soggettoField;

        private string ragione_socialeField;

        private string comune_sedeField;

        private string prov_sedeField;

        /// <remarks/>
        public string id_soggetto
        {
            get
            {
                return this.id_soggettoField;
            }
            set
            {
                this.id_soggettoField = value;
            }
        }

        /// <remarks/>
        public string ragione_sociale
        {
            get
            {
                return this.ragione_socialeField;
            }
            set
            {
                this.ragione_socialeField = value;
            }
        }

        /// <remarks/>
        public string comune_sede
        {
            get
            {
                return this.comune_sedeField;
            }
            set
            {
                this.comune_sedeField = value;
            }
        }

        /// <remarks/>
        public string prov_sede
        {
            get
            {
                return this.prov_sedeField;
            }
            set
            {
                this.prov_sedeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class chiudi_conti
    {

        private string id_fornituraField;

        private string num_recordField;

        private conto_chiuso[] conto_chiusoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string id_fornitura
        {
            get
            {
                return this.id_fornituraField;
            }
            set
            {
                this.id_fornituraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string num_record
        {
            get
            {
                return this.num_recordField;
            }
            set
            {
                this.num_recordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conto_chiuso")]
        public conto_chiuso[] conto_chiuso
        {
            get
            {
                return this.conto_chiusoField;
            }
            set
            {
                this.conto_chiusoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class conto_chiuso
    {

        private string progField;

        private string id_contoField;

        private cod_rete cod_reteField;

        private string cod_concField;

        private causale causaleField;

        private System.DateTime data_cessazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string prog
        {
            get
            {
                return this.progField;
            }
            set
            {
                this.progField = value;
            }
        }

        /// <remarks/>
        public string id_conto
        {
            get
            {
                return this.id_contoField;
            }
            set
            {
                this.id_contoField = value;
            }
        }

        /// <remarks/>
        public cod_rete cod_rete
        {
            get
            {
                return this.cod_reteField;
            }
            set
            {
                this.cod_reteField = value;
            }
        }

        /// <remarks/>
        public string cod_conc
        {
            get
            {
                return this.cod_concField;
            }
            set
            {
                this.cod_concField = value;
            }
        }

        /// <remarks/>
        public causale causale
        {
            get
            {
                return this.causaleField;
            }
            set
            {
                this.causaleField = value;
            }
        }

        /// <remarks/>
        public System.DateTime data_cessazione
        {
            get
            {
                return this.data_cessazioneField;
            }
            set
            {
                this.data_cessazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum causale
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mod_residenza
    {

        private string id_fornituraField;

        private string num_recordField;

        private conto_mod[] conto_modField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string id_fornitura
        {
            get
            {
                return this.id_fornituraField;
            }
            set
            {
                this.id_fornituraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string num_record
        {
            get
            {
                return this.num_recordField;
            }
            set
            {
                this.num_recordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conto_mod")]
        public conto_mod[] conto_mod
        {
            get
            {
                return this.conto_modField;
            }
            set
            {
                this.conto_modField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class conto_mod
    {

        private string progField;

        private string id_contoField;

        private cod_rete cod_reteField;

        private string cod_concField;

        private string prov_residenzaField;

        private System.DateTime data_movimentoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string prog
        {
            get
            {
                return this.progField;
            }
            set
            {
                this.progField = value;
            }
        }

        /// <remarks/>
        public string id_conto
        {
            get
            {
                return this.id_contoField;
            }
            set
            {
                this.id_contoField = value;
            }
        }

        /// <remarks/>
        public cod_rete cod_rete
        {
            get
            {
                return this.cod_reteField;
            }
            set
            {
                this.cod_reteField = value;
            }
        }

        /// <remarks/>
        public string cod_conc
        {
            get
            {
                return this.cod_concField;
            }
            set
            {
                this.cod_concField = value;
            }
        }

        /// <remarks/>
        public string prov_residenza
        {
            get
            {
                return this.prov_residenzaField;
            }
            set
            {
                this.prov_residenzaField = value;
            }
        }

        /// <remarks/>
        public System.DateTime data_movimento
        {
            get
            {
                return this.data_movimentoField;
            }
            set
            {
                this.data_movimentoField = value;
            }
        }
    }

}